"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, LoaderCircle } from "lucide-react";

type Fields = "assumptions" | "design" | "tradeoffs" | "edgeCases";
export function SubmissionForm({ problemId }: { problemId: string }) {
  const router=useRouter(); const [pending,setPending]=useState(false); const [errors,setErrors]=useState<Partial<Record<Fields,string[]>>>({}); const [formError,setFormError]=useState("");
  const idempotencyKey = useRef<string | null>(null);
  async function submit(formData:FormData){setPending(true);setErrors({});setFormError("");try{idempotencyKey.current??=crypto.randomUUID();const response=await fetch("/api/attempts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({problemId,assumptions:formData.get("assumptions"),design:formData.get("design"),tradeoffs:formData.get("tradeoffs"),edgeCases:formData.get("edgeCases"),idempotencyKey:idempotencyKey.current})});const result=await response.json();if(!response.ok){setErrors(result.fields??{});setFormError(result.error??"Submission failed.");return}router.push(`/attempts/${result.attemptId}`)}catch{setFormError("We could not reach the evaluator. Your form is still here—please retry.")}finally{setPending(false)}}
  const fields:{name:Fields;label:string;help:string;placeholder:string}[]=[{name:"assumptions",label:"1. Assumptions and scope",help:"State what you are solving—and deliberately not solving.",placeholder:"Example: One facility, multiple floors, and a single entry gate for this MVP..."},{name:"design",label:"2. Classes, responsibilities, and interactions",help:"Describe the core objects, what each owns, and how a main use case flows.",placeholder:"ParkingLot owns floors and coordinates entry. SpotAssignmentPolicy selects a compatible spot..."},{name:"tradeoffs",label:"3. Decisions and trade-offs",help:"Explain why you chose this design and what alternatives you rejected.",placeholder:"I separated pricing behind a policy because rates change independently..."},{name:"edgeCases",label:"4. Edge cases and testing",help:"Show how the design behaves when things go wrong or happen concurrently.",placeholder:"Two entries requesting the final compatible spot; payment failure during exit..."}];
  return <form action={submit} className="submission-form">{formError&&<p className="form-error" role="alert">{formError}</p>}{fields.map((field,index)=><div className="field" key={field.name}><div className="field-heading"><span>0{index+1}</span><div><label htmlFor={field.name}>{field.label.replace(/^\d+\.\s*/,"")}</label><small>{field.help}</small></div></div><textarea id={field.name} name={field.name} placeholder={field.placeholder} required aria-invalid={Boolean(errors[field.name])}/>{errors[field.name]?.map(error=><p className="error-text" key={error}>{error}</p>)}</div>)}<div className="submit-row"><p><strong>Safe to submit.</strong> Your answer is stored before evaluation begins.</p><button className="button primary" disabled={pending} type="submit">{pending?<><LoaderCircle size={17}/> Evaluating design…</>:<>Submit for feedback <ArrowRight size={17}/></>}</button></div></form>;
}
